
package uk.gov.nationalarchives.pronom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PronomService", targetNamespace = "http://pronom.nationalarchives.gov.uk")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PronomService {


    /**
     *  Returns the current signature file version 
     * 
     * @param deprecated
     * @param version
     */
    @WebMethod(action = "http://pronom.nationalarchives.gov.uk:getSignatureFileVersionV1In")
    @RequestWrapper(localName = "getSignatureFileVersionV1", targetNamespace = "http://pronom.nationalarchives.gov.uk", className = "uk.gov.nationalarchives.pronom.GetSignatureFileVersionV1")
    @ResponseWrapper(localName = "getSignatureFileVersionV1Response", targetNamespace = "http://pronom.nationalarchives.gov.uk", className = "uk.gov.nationalarchives.pronom.GetSignatureFileVersionV1Response")
    public void getSignatureFileVersionV1(
        @WebParam(name = "Version", targetNamespace = "http://pronom.nationalarchives.gov.uk", mode = WebParam.Mode.OUT)
        Holder<Version> version,
        @WebParam(name = "Deprecated", targetNamespace = "http://pronom.nationalarchives.gov.uk", mode = WebParam.Mode.OUT)
        Holder<Boolean> deprecated);

    /**
     *  Returns the current signature file 
     * 
     * @return
     *     returns uk.gov.nationalarchives.pronom.SigFile
     */
    @WebMethod(action = "http://pronom.nationalarchives.gov.uk:getSignatureFileV1In")
    @WebResult(name = "SignatureFile", targetNamespace = "http://pronom.nationalarchives.gov.uk")
    @RequestWrapper(localName = "getSignatureFileV1", targetNamespace = "http://pronom.nationalarchives.gov.uk", className = "uk.gov.nationalarchives.pronom.GetSignatureFileV1")
    @ResponseWrapper(localName = "getSignatureFileV1Response", targetNamespace = "http://pronom.nationalarchives.gov.uk", className = "uk.gov.nationalarchives.pronom.GetSignatureFileV1Response")
    public SigFile getSignatureFileV1();

}
