---
language: "python"
python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - "pip install -U pip flake8 pep257 pytest-cov codecov codacy-coverage"
  - "python setup.py build"
  - "python setup.py bdist --formats=zip"
  - "python setup.py install"

script:
  - "flake8 ./fido"
  # pep257: fido.py is WIP
  - 'pep257 --match="(?!fido).*\.py" ./fido'
  - "pytest --cov=fido"

after_success:
  - "coverage xml"
  - "codecov"
  - "python-codacy-coverage -r coverage.xml"
